apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: costspike
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: costspike-backend-deploy
        image: shubhsjadhav95/costspike-backend:v3
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-key
