apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: costspike
type: Opaque
data:
  access-key: QUtJQVZCVEM3RjRUUldRV0FIU1gK
  secret-key: MlpxckJheDNIaGpscmVidWtaMCthbEVIOHY4eDl6ZFM1WHhKWnNzaAo=