spring.application.name=aws-alert

aws.region=us-east-1
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
<<<<<<< HEAD
aws.bucketName=shubhsjadhav95-lambda-alert-95
=======
aws.bucketName=shubhsjadhav95-lambda-alert

>>>>>>> 49683a48882ed388784dd19ab59a0654f0a7dd70

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always