pipeline {
agent any


parameters {
    string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region')
    string(name: 'AWS_ACCOUNT_ID', defaultValue: '431618680847', description: 'AWS Account ID')
    string(name: 'ECR_REPO_NAME', defaultValue: 'costspike-frontend', description: 'ECR Repository Name')
    string(name: 'VERSION', defaultValue: 'latest', description: 'Docker Image Version')
    string(name: 'CLUSTER_NAME', defaultValue: 'costspike-cluster', description: 'EKS Cluster Name')
}

tools {
    jdk 'jdk'
    nodejs 'nodejs'
}

environment {
    SCANNER_HOME = tool('sonarqube-scanner')
    FRONTEND_DIR = 'frontend/aws-alert-frontend'
    IMAGE_URI = "${params.AWS_ACCOUNT_ID}.dkr.ecr.${params.AWS_REGION}.amazonaws.com/${params.ECR_REPO_NAME}"
}

stages {

    stage('Checkout Source Code') {
        steps {
            git branch: 'main',
                url: 'https://github.com/shubhsJadhav95/AWS_COST_ALERT.git'
        }
    }

    stage('Verify Workspace') {
        steps {
            sh '''
            pwd
            ls -la
            find . -name package.json
            '''
        }
    }

    stage('SonarQube Analysis') {
        steps {
            dir("${FRONTEND_DIR}") {
                withSonarQubeEnv('sonar-server') {
                    sh """
                    ${SCANNER_HOME}/bin/sonar-scanner \
                    -Dsonar.projectName=costspike-frontend \
                    -Dsonar.projectKey=costspike-frontend
                    """
                }
            }
        }
    }

    stage('Quality Gate') {
        steps {
            timeout(time: 10, unit: 'MINUTES') {
                waitForQualityGate abortPipeline: true
            }
        }
    }

    stage('OWASP Dependency Check') {
        steps {
            dir("${FRONTEND_DIR}") {
                dependencyCheck(
                    additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit',
                    odcInstallation: 'DP-Check'
                )

                dependencyCheckPublisher(
                    pattern: '**/dependency-check-report.xml'
                )
            }
        }
    }
//
    stage('Install Dependencies') {
        steps {
            dir("${FRONTEND_DIR}") {
                sh '''
                npm install  
                '''
            }
        }
    }

    stage('Trivy Filesystem Scan') {
        steps {
            dir("${FRONTEND_DIR}") {
                sh '''
                trivy fs --format table -o trivy-report.txt .
                '''
            }
        }
    }

    stage('Build Docker Image') {
        steps {
            dir("${FRONTEND_DIR}") {
                sh '''
                docker build -t ${ECR_REPO_NAME}:${BUILD_NUMBER} .
                '''
            }
        }
    }

    stage('Create ECR Repository') {
        steps {
            withCredentials([
                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
            ]) {

                sh '''
                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY

                aws ecr describe-repositories \
                --repository-names ${ECR_REPO_NAME} \
                --region ${AWS_REGION} || \
                aws ecr create-repository \
                --repository-name ${ECR_REPO_NAME} \
                --region ${AWS_REGION}
                '''
            }
        }
    }

    stage('Login to ECR') {
        steps {
            withCredentials([
                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
            ]) {

                sh '''
                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY

                aws ecr get-login-password \
                --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }
    }

    stage('Tag Docker Image') {
        steps {
            sh '''
            docker tag ${ECR_REPO_NAME}:${BUILD_NUMBER} ${IMAGE_URI}:${BUILD_NUMBER}
            docker tag ${ECR_REPO_NAME}:${BUILD_NUMBER} ${IMAGE_URI}:latest
            '''
        }
    }

    stage('Push Docker Image') {
        steps {
            sh '''
            docker push ${IMAGE_URI}:${BUILD_NUMBER}
            docker push ${IMAGE_URI}:latest
            '''
        }
    }

  stage('Configure EKS Access') {
    steps {
        withCredentials([
            string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
            string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
        ]) {
            sh '''
                set -e

                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
                export AWS_DEFAULT_REGION=${AWS_REGION}

                aws sts get-caller-identity

                aws eks update-kubeconfig \
                    --region ${AWS_REGION} \
                    --name ${CLUSTER_NAME}

                # Save kubeconfig path for later stages
                echo "export KUBECONFIG=/var/lib/jenkins/.kube/config" > kube.env
            '''
        }
    }
}

    stage('Update Deployment Image') {
        steps {
            script {
                def IMAGE_NAME = "${IMAGE_URI}:${params.VERSION}"

                sh """
                sed -i 's|image: .*|image: ${IMAGE_NAME}|' k8s/frontend/deployment.yml
                """
            }
        }
    }

   stage('Deploy to EKS') {
    steps {
        withCredentials([
            string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
            string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
        ]) {
            sh '''
                set -e

                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
                export AWS_DEFAULT_REGION=${AWS_REGION}

                export KUBECONFIG=/var/lib/jenkins/.kube/config
                kubectl create namespace costspike
                kubectl apply -f k8s/frontend/deployment.yml
                kubectl apply -f k8s/frontend/service.yml
            '''
        }
    }
}

    stage('Verify Deployment') {
        steps {
            withCredentials([
                string(credentialsId: 'AWS_ACCESS_KEY', variable: 'AWS_ACCESS_KEY'),
                string(credentialsId: 'AWS_SECRET_KEY', variable: 'AWS_SECRET_KEY')
            ]) {
                sh '''
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
                    export AWS_DEFAULT_REGION=${AWS_REGION}
    
                    export KUBECONFIG=/var/lib/jenkins/.kube/config
    
                    kubectl get pods -A
                    kubectl get svc -A
                '''
            }
        }
    }
    stage('Cleanup Docker Images') {
    steps {
        sh '''
            docker rmi ${IMAGE_URI}:${BUILD_NUMBER} || true
            docker rmi ${IMAGE_URI}:latest || true
            docker image prune -f
        '''
    }
}
}

post {

    success {
        echo 'Pipeline completed successfully'
    }

    failure {
        echo 'Pipeline failed'
    }

    always {
        archiveArtifacts artifacts: '**/trivy-report.txt', allowEmptyArchive: true
    }
}


}
